### ISSUE TITLE
Port Wage Garnishment Dispute tool to JSON Schema

### ISSUE THREAD

**Issue by orlando** [debtcollective/disputes#10]
We need to port the [Wage Garnishment Dispute tool definition](https://github.com/debtcollective/dispute-tools/blob/master/lib/data/form-definitions/wage-garnishment-dispute.js) to JSON Schema.

## Acceptance Criteria

- Wage Garnishment Dispute should work using JSON Schema

**Comment by duranmla** [comment]
All the schemas have been exported, today I will make the PR EOD. 🚀 Feel free to take a look at the changes at https://github.com/debtcollective/disputes/tree/ad/10

**Comment by duranmla** [comment]
I couldn't resist making the PR 🎉
