### ISSUE TITLE
Research Document generation service

### ISSUE THREAD

**Issue by orlando** [debtcollective/disputes#16]
We want to create a service that handles the document generation process. Currently, we have two ways of creating documents:

- pug (html)
- pdf (filling pdfs forms with data)

We want to have this same functionality but deployed separately from the Disputes application.

We came with a stack that can do the job:

- [SQS](https://aws.amazon.com/sqs/)
- [Serverless Framework](https://serverless.com/) using [SQS triggers](https://serverless.com/framework/docs/providers/aws/events/sqs/)
- [Puppeteer](https://github.com/GoogleChrome/puppeteer) for html to pdf

As part of the research, we expect to define:

- How we will integrate SQS with Serverless to generate documents.
- How we will handle errors when generating documents.
- How we will notify other applications about the status of the generated documents.
- How we will handle uploads to S3 once the documents are generated.
- How we will achieve the same functionality we have in our current documentation generation pipeline.

> Implementation will be done in #36 

## Acceptance Criteria

- Research and write a spec to discuss the implementation strategy for this service.

**Comment by duranmla** [comment]
We've talked about this document: https://www.notion.so/duranmla/16-Document-generation-service-1a475f9e1f444b4ba62b787c22d23f47 nevertheless, it seems to bring a complexity that is not needed now. Thus, we're going to implement the following:

```
1. User completes dispute
2. afterSave or on state change to completed (we will use a state machine for this) we will queue a message in SQS
3. SQS triggers a lambda function (our document generation function) and does the work
  3.1 Function looks for the Dispute model
  3.2 Function looks for template in the files (we will have access to these files from the lambda function)
  3.3 With the template it will generate the docs
  3.4 Upload the docs to s3
  3.5 Persist data to the database (Function will have access to the same database as the disputes app)
  3.6 Notify user somehow (optional)
```

Bear in mind that the communication will be system to system after the model of dispute finish to save all the data.

**Comment by duranmla** [comment]
Implementation at: #36
