### ISSUE TITLE
Implement Document generation service

### ISSUE THREAD

**Issue by orlando** [debtcollective/disputes#36]
Once we have the research done from #16. We will need to implement this according to the spec.

## Acceptance Criteria

- Document generation is implemented according to the spec.

**Comment by duranmla** [comment]
Currently, regarding this we have:
- Created a project based on https://github.com/sambaiz/puppeteer-lambda-starter-kit with all updated dependencies
- Check some principles of functionality from https://github.com/esbenp/pdf-bot
- Use https://github.com/westy92/html-pdf-chrome in addition to lambda puppeteer configuration to being able to create PDF locally.

At this point, over minor static updates related to code taken from other projects, what we'll do is to set up the SQS endpoint to trigger the same process than locally.

**Comment by duranmla** [comment]
At this point, I have uploaded more about the implementation for the document generation service aligned with the ideas discussed with @orlando 

The last commit is 33194cd80022ec7293cb61d058f54072c6db2067

Where the service is capable of creating PDF files using HBS templates, the remaining work is to be able to upload those files into S3 bucket and interact with the models properly

**Comment by duranmla** [comment]
We are missing:
- Add all templates on `.hbs` equivalent
- Create all document types classes
- Manage real models to get the database information
- Support FDF

**Comment by orlando** [comment]
We have reached a point where we are splitting the work into multiple tickets now at https://github.com/debtcollective/document-service. We will close this one an estimate the others
