### ISSUE TITLE
Add Dispute model

### ISSUE THREAD

**Issue by orlando** [debtcollective/disputes#61]
We are using https://vincit.github.io/objection.js/ as our ORM, we want to create a model to store the Dispute information.

We need to define the data schema Dispute will have and standardize the way we store data across different tools.

The data from the different tools will be validated using JSON schema, so as part of the saving/updating process we need to take this into account. Also, we want to let the user save their work before submitting (functionality for a "Save Progress" button). In this case, we don't have to validate the data.

## Acceptance Criteria

- Create Dispute model using Objection.js
- Dispute should validate the data when submitting a form

**Comment by duranmla** [comment]
Is this ready then? Or do we need something extra for it? If we need to keep working on this we should try to being explicit about the about effort it cost us as it doesn't feel like 5 points

**Comment by orlando** [comment]
@duranmla yeah, I'll close this when I move the model to the it's own package. And yes this was way more than 5 points.

I'll create follow up tickets when we merge https://github.com/debtcollective/disputes/pull/161

**Comment by duranmla** [comment]
Not sure what are we doing here. You move from 5 to 3 because it is almost ready? Why we haven't merged the PR #161 ? On top of that this ticket from scratch would have been evaluated at leats with 13 points according to our guidelines. In that sense, it will depend upon the current state to update the estimation.

**Comment by orlando** [comment]
Closed in #160
