### ISSUE TITLE
Research using JSON Schema for tools definitions

### ISSUE THREAD

**Issue by orlando** [debtcollective/disputes#7]
The current version of the tools definition uses a custom implementation based on [Checkit](https://github.com/tgriesser/checkit) and other custom tools. This has multiple disadvantages like not being able to use standard tooling and having to implement any limitation the library has (at the moment we have code that extends it).

Form definitions as are currently called have everything a tool needs to have, including the text we display for the tools description and how we store the data, here's an example https://github.com/debtcollective/dispute-tools/blob/master/lib/data/form-definitions/credit-report-dispute.js.

To improve what we have and reduce the amount of code we maintain, we want to use [JSON Schema](https://json-schema.org/) to define our tools and use it as the source of truth for the tool.

As part of the research, we expect to define:

- How we will store the data in the database
- How we will handle validations
- How we will render forms and wizards from the tool definition

## Acceptance Criteria

- Create a spec that includes a way for us to adopt JSON schema as our tool definition framework.

**Comment by orlando** [comment]
We made progress with the research last week, we are reducing the number of points from 13 to 8 to account this work.

**Comment by duranmla** [comment]
Basically, at this point, we have made research that has suggested the following options:

1. https://github.com/mozilla-services/react-jsonschema-form
2. https://github.com/jquense/yup + https://github.com/jaredpalmer/formik + https://github.com/flipbyte/formik-json-schema

Both of them has they pros and cons, for option 1, the challenge is that as everything is built-in there are also more complexity within the code that may make not that easy to add new custom UI for it. Option 2, has the advantage that every piece of the puzzle is isolated in a projected dedicated to it, which makes easier to reasoning over the implementation of the forms, nevertheless, the JSON to form project is not very popular and we can fall into the scenario where we need to maintain a fork of that project if we found it is not solid enough.

**Comment by duranmla** [comment]
With the above being said, the idea now is to create a playground where to test those solutions to see how the code looks like and being able to take a decision based upon those prototypes.

- [ ] Create a branch with mozilla's project
- [ ] Create a branch with formik + yup setup
- [ ] Fill the prototype with data from a ported form like #8 

After the above we will discuss which option take, besides, there still one thing missing at it would be how to store this information, while we know that we are dealing with JSON we need to ensure how the queries are going to be performed and the tradeoff of it.

- [ ] Suggest a basic structure for storing JSON schemas, forms and data overall related to it.

**Comment by duranmla** [comment]
I had some issues trying to use our project of tools that don't allow me to write a component because "react" weren't in the scope, it may be something silly related to how "next app" works but I will make the prototypes in an isolated "create react project" to achieve the goal of testing the tools

**Comment by duranmla** [comment]
Digging more into the Mozilla project I have found this:
- https://github.com/mozilla-services/react-jsonschema-form/blob/889871f90c6b03aed4df431d92fa60de10be24a6/docs/advanced-customization.md
- https://github.com/mozilla-services/react-jsonschema-form/pull/1152

Basically, there is support for advancing customization, not sure how difficult will be to use it because is not crystal clear with a doc that is a little bit dense, there is a pending PR for templating (everyone looks excited about it but it has conflicts).

I get lost a little bit with the docs but I will aim to port the General Dispute and try to solve the challenges there (select for states and the composition of debt type and amount) mirroring the design we have but Material UI like will give us more info about this.

**Comment by orlando** [comment]
This looks good, probably is the way to go when we need to do customizations

**Comment by duranmla** [comment]
The problem I had was this one:
![image](https://user-images.githubusercontent.com/1425162/56721834-03c31900-6746-11e9-9bb4-6ded84f86df9.png)

The branch has the WIP commit at https://github.com/debtcollective/disputes/tree/ad/mozilla-services/react-jsonschema-form

At that point, I didn't want to spend time there and I move to a create react project instead, but the error message is very specific the error is within the library somehow.

**Comment by orlando** [comment]
@duranmla I'll check out this on my local, this looks really weird.

**Comment by duranmla** [comment]
In my isolated environment, I have made some progress using Mozilla's project _(see picture below)_ now what I need is to satisfy some aesthetic UI related needs and the behavior we have with "other" debt type - which I know where to look to do it -.

![image](https://user-images.githubusercontent.com/1425162/56788839-cff8f980-6800-11e9-8853-4a8d31d509a8.png)

_PD: all that has been rendered with just a JSON object and we have states options, debt types options and date inputs too_

**Comment by duranmla** [comment]
At this point this is what I have:

![http://recordit.co/dQhCsD5hkT](http://recordit.co/dQhCsD5hkT.gif)

Now the following things to define is the document to expose my idea to work with the forms. In my opinion, the material styles need to be made by us and we need to inject a grid system; another alternative will be to work with material-ui grid system (I have to check what it is) and classes from material-ui if they are not scoped by component and apply them to our UI schema.

On top of that, I have to expose how I think we can save the data, sort of:
- JSON Schemas
- UI Schemas
- Dependencies (I will talk more about it in the doc)
- FormData can be saved by field as any other record like: `{ title: 'foo', desc: 'bla' }` -> it will insert on the table of disputes a new entry with the column title = to foo and desc column = to bla

**Comment by duranmla** [comment]
The isolated place where I am making that prototyping is https://github.com/duranmla/forms feel free to check it out.

**Comment by duranmla** [comment]
After defining the way we want to work with forms what I need to do now is to:
- [ ]  Integrate [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) in disputes project
- [ ]  Map form definition to Material UI components

With that I will be able to make the PR

**Comment by duranmla** [comment]
What I have realized is that we do not have anything yet for static testing of our app (eslint, flow) and "prettier" to format the code accordingly. Before moving any forward I will add those in a separated PR since it is the first level of testing in our code.

**Comment by duranmla** [comment]
I decide to skip the setup seems this task is blocked for pretty much everything and I started today with the mapping and further implementation of the form as we want them.

With the above being said, I am currently mapping the components and now I were looking for the easier and more reliable way to handle the values and states of those components to keep the Mozilla built-in behavior, what I come up with is to mirror the state of our custom components within the given HTML raw components that Mozilla gives us.

**Context:** the project give us the alternative to change the layout and fields itself in two separate ways, but I do not want to break the built-in behavior too much, instead I am looking for rendering our custom component alongside hidden built in one and whenever we type in the custom the hidden mirror the activity programmatically.

As my intended behavior is a custom complexity injecting into the project I will aim to write a test on every case we need to do this behavior (now we need selects and inputs). 

My work in progress is at [1d976c12be5b60724a94a92bf99fb9952f8e2eaa](https://github.com/debtcollective/disputes/commit/1d976c12be5b60724a94a92bf99fb9952f8e2eaa)

**Comment by duranmla** [comment]
While we already support error state within the form, there are some questions to be answered.
- Currently, fields that user haven't touched doesn't show an error until submit
- Some fields never show an error until submit

I will try to address those today, nevertheless, if I can not find the solution I will create an issue and make the PR either way.

**Comment by duranmla** [comment]
I have pushed several updates related to this topic currently the only thing I can see missing is that the select input doesn't recognize the option selected as valid. Like so:
![image](https://user-images.githubusercontent.com/1425162/57211057-3808c600-6fdf-11e9-85dd-5579963311c1.png)

Other than that, seems like we are ready to make the PR and work with the grid solution for forms.

**Comment by duranmla** [comment]
Again, the latest updates can be check at https://github.com/debtcollective/disputes/compare/ad/mozilla-services/react-jsonschema-form

**Comment by orlando** [comment]
I created https://github.com/debtcollective/disputes/issues/61 as a follow up work for this. We are moving the data persistence part of the ticket to a new one
