### ISSUE TITLE
Port Tax Offset Dispute tool to JSON Schema

### ISSUE THREAD

**Issue by orlando** [debtcollective/disputes#9]
We need to port the [Tax Offset Dispute tool definition](https://github.com/debtcollective/dispute-tools/blob/master/lib/data/form-definitions/tax-offset-dispute.js) to JSON Schema.

## Acceptance Criteria

- Tax Offset Dispute tool should work using JSON Schema

**Comment by duranmla** [comment]
After checking some of the needs for this issue, currently, the next things to do are:
- [ ]  Number field should distinguish between currency, telephones or just number
- [ ]  Date field need a way to handle title and help
- [ ]  Port schema to satisfy behavior of FFEL block

All of those even before mapping radio buttons and checkboxes to material UI.

**Comment by duranmla** [comment]
I have created a new branch from the latest PR with code related to adding type B _(which end up by being the exact same form than type A)_ and adding type C _(which I need to develop one custom components and add branches for some special cases)_

https://github.com/debtcollective/disputes/compare/ad/9-type-a-b

**Comment by duranmla** [comment]
At this point we have added a factory for those "yes/no" questions that support branching after an option is selected, this, without doubt, will make this process easier since requires less mental effort to write the schema _(which is fairly long and nested)_.

**Comment by duranmla** [comment]
At this point, we need to **map the Radio buttons**.
What would be great is to have the E2E tests in place now that we have cypress _(we can talk about it in the next meeting)_
